QWEN_SUPPORTED_LANGUAGES = {
    "Afrikaans",
    "Arabic (Standard, Najdi, Levantine, Egyptian, Moroccan, Mesopotamian, Ta'izzi-Adeni, Tunisian)",
    "Armenian",
    "Assamese",
    "Asturian",
    "Awadhi",
    "Balinese",
    "Banjar",
    "Bashkir",
    "Basque",
    "Belarusian",
    "Bengali",
    "Bhojpuri",
    "Bosnian",
    "Bulgarian",
    "Burmese",
    "Catalan",
    "Cebuano",
    "Chhattisgarhi",
    "Chinese (Simplified Chinese, Traditional Chinese, Cantonese)",
    "Croatian",
    "Czech",
    "Danish",
    "Dari",
    "Dutch",
    "Eastern Yiddish",
    "English",
    "Estonian",
    "Faroese",
    "Finnish",
    "French",
    "Friulian",
    "Galician",
    "Georgian",
    "German",
    "Greek",
    "Gujarati",
    "Haitian",
    "Hebrew",
    "Hindi",
    "Hungarian",
    "Icelandic",
    "Iloko",
    "Indonesian",
    "Irish",
    "Italian",
    "Japanese",
    "Javanese",
    "Kabuverdianu",
    "Kannada",
    "Kazakh",
    "Khmer",
    "Korean",
    "Lao",
    "Latvian",
    "Ligurian",
    "Limburgish",
    "Lithuanian",
    "Lombard",
    "Luxembourgish",
    "Macedonian",
    "Magahi",
    "Maithili",
    "Malay",
    "Malayalam",
    "Maltese",
    "Marathi",
    "Minangkabau",
    "Nepali",
    "North Azerbaijani",
    "Northern Uzbek",
    "Norwegian (Bokmål)",
    "Norwegian (Nynorsk)",
    "Occitan",
    "Oriya",
    "Pangasinan",
    "Papiamento",
    "Persian",
    "Polish",
    "Portuguese",
    "Punjabi",
    "Romanian",
    "Russian",
    "Sardinian",
    "Serbian",
    "Sicilian",
    "Silesian",
    "Sindhi",
    "Sinhala",
    "Slovak",
    "Slovenian",
    "Spanish",
    "Sundanese",
    "Swahili",
    "Swedish",
    "Tagalog",
    "Tajik",
    "Tamil",
    "Tatar",
    "Telugu",
    "Thai",
    "Tok Pisin",
    "Tosk Albanian",
    "Turkish",
    "Ukrainian",
    "Urdu",
    "Venetian",
    "Vietnamese",
    "Waray (Philippines)",
    "Welsh",
}
