REMEDY_SUPPORTED_LANGUAGES = {
    "Afrikaans",
    "Akan",
    "Amharic",
    "Modern Standard Arabic (Romanized)",
    "Assamese",
    "Bashkir",
    "Bambara",
    "Belarusian",
    "Bengali",
    "Bosnian",
    "Bulgarian",
    "Catalan",
    "Czech",
    "Welsh",
    "Danish",
    "German",
    "Dzongkha",
    "Greek",
    "English",
    "Esperanto",
    "Estonian",
    "Basque",
    "Ewe",
    "Faroese",
    "Fijian",
    "Finnish",
    "French",
    "Scottish Gaelic",
    "Irish",
    "Galician",
    "Guarani",
    "Gujarati",
    "Haitian Creole",
    "Hausa",
    "Hebrew",
    "Hindi",
    "Croatian",
    "Hungarian",
    "Armenian",
    "Igbo",
    "Indonesian",
    "Icelandic",
    "Italian",
    "Javanese",
    "Japanese",
    "Kannada",
    "Kashmiri (Devanagari script)",
    "Georgian",
    "Kazakh",
    "Khmer",
    "Kikuyu",
    "Kinyarwanda",
    "Kyrgyz",
    "Kikongo",
    "Korean",
    "Lao",
    "Latvian",
    "Limburgish",
    "Lingala",
    "Lithuanian",
    "Luxembourgish",
    "Luba-Kasai",
    "Ganda",
    "Malayalam",
    "Marathi",
    "Macedonian",
    "Maltese",
    "Maori",
    "Burmese",
    "Dutch",
    "Norwegian (Nynorsk)",
    "Norwegian (Bokmål)",
    "Nepali",
    "Nyanja",
    "Occitan",
    "Odia",
    "Dari",
    "Pashto",
    "Polish",
    "Portuguese",
    "Romanian",
    "Rundi",
    "Russian",
    "Sango",
    "Sanskrit",
    "Sinhala",
    "Slovak",
    "Slovenian",
    "Samoan",
    "Shona",
    "Sindhi",
    "Somali",
    "Southern Sotho",
    "Spanish",
    "Sardinian",
    "Serbian",
    "Swati",
    "Sundanese",
    "Swedish",
    "Swahili",
    "Tamil",
    "Tatar",
    "Telugu",
    "Tajik",
    "Tagalog",
    "Thai",
    "Tigrinya",
    "Tswana",
    "Tsonga",
    "Turkmen",
    "Turkish",
    "Twi",
    "Uyghur",
    "Ukrainian",
    "Urdu",
    "Vietnamese",
    "Wolof",
    "Xhosa",
    "Yoruba",
    "Chinese (Traditional)",
    "Zulu",
}


REMEDY_ISO_MAP = {
    "af": "Afrikaans",
    "ak": "Akan",
    "am": "Amharic",
    "ar": "Modern Standard Arabic (Romanized)",
    "as": "Assamese",
    "ba": "Bashkir",
    "bm": "Bambara",
    "be": "Belarusian",
    "bn": "Bengali",
    "bs": "Bosnian",
    "bg": "Bulgarian",
    "ca": "Catalan",
    "cs": "Czech",
    "cy": "Welsh",
    "da": "Danish",
    "de": "German",
    "dz": "Dzongkha",
    "el": "Greek",
    "en": "English",
    "eo": "Esperanto",
    "et": "Estonian",
    "eu": "Basque",
    "ee": "Ewe",
    "fo": "Faroese",
    "fj": "Fijian",
    "fi": "Finnish",
    "fr": "French",
    "gd": "Scottish Gaelic",
    "ga": "Irish",
    "gl": "Galician",
    "gn": "Guarani",
    "gu": "Gujarati",
    "ht": "Haitian Creole",
    "ha": "Hausa",
    "he": "Hebrew",
    "hi": "Hindi",
    "hr": "Croatian",
    "hu": "Hungarian",
    "hy": "Armenian",
    "ig": "Igbo",
    "id": "Indonesian",
    "is": "Icelandic",
    "it": "Italian",
    "jv": "Javanese",
    "ja": "Japanese",
    "kn": "Kannada",
    "ks": "Kashmiri (Devanagari script)",
    "ka": "Georgian",
    "kk": "Kazakh",
    "km": "Khmer",
    "ki": "Kikuyu",
    "rw": "Kinyarwanda",
    "ky": "Kyrgyz",
    "kg": "Kikongo",
    "ko": "Korean",
    "lo": "Lao",
    "lv": "Latvian",
    "li": "Limburgish",
    "ln": "Lingala",
    "lt": "Lithuanian",
    "lb": "Luxembourgish",
    "lu": "Luba-Kasai",
    "lg": "Ganda",
    "ml": "Malayalam",
    "mr": "Marathi",
    "mk": "Macedonian",
    "mt": "Maltese",
    "mi": "Maori",
    "my": "Burmese",
    "nl": "Dutch",
    "nn": "Norwegian (Nynorsk)",
    "nb": "Norwegian (Bokmål)",
    "ne": "Nepali",
    "ny": "Nyanja",
    "oc": "Occitan",
    "or": "Odia",
    "fa": "Dari",
    "ps": "Pashto",
    "pl": "Polish",
    "pt": "Portuguese",
    "ro": "Romanian",
    "rn": "Rundi",
    "ru": "Russian",
    "sg": "Sango",
    "sa": "Sanskrit",
    "si": "Sinhala",
    "sk": "Slovak",
    "sl": "Slovenian",
    "sm": "Samoan",
    "sn": "Shona",
    "sd": "Sindhi",
    "so": "Somali",
    "st": "Southern Sotho",
    "es": "Spanish",
    "sc": "Sardinian",
    "sr": "Serbian",
    "ss": "Swati",
    "su": "Sundanese",
    "sv": "Swedish",
    "sw": "Swahili",
    "ta": "Tamil",
    "tt": "Tatar",
    "te": "Telugu",
    "tg": "Tajik",
    "tl": "Tagalog",
    "th": "Thai",
    "ti": "Tigrinya",
    "tn": "Tswana",
    "ts": "Tsonga",
    "tk": "Turkmen",
    "tr": "Turkish",
    "tw": "Twi",
    "ug": "Uyghur",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "vi": "Vietnamese",
    "wo": "Wolof",
    "xh": "Xhosa",
    "yo": "Yoruba",
    "zh": "Chinese (Traditional)",
    "zu": "Zulu",
}
